return {
	{
		id = "rightSlash",
		assetId = "rbxassetid://87593220907984",
		animationId = "rightSlash",
		name = "Slash (Right)",
		kind = "attack",
		direction = "right",
		description = "A simple horizontal slash, from left to right.",
	},
	{
		id = "leftSlash",
		assetId = "rbxassetid://95127690189373",
		animationId = "leftSlash",
		name = "Slash (Left)",
		kind = "attack",
		direction = "left",
		description = "A simple horizontal slash, from right to left.",
	},
	{
		id = "upSlash",
		assetId = "rbxassetid://100591332217715",
		animationId = "upSlash",
		name = "Slash (Up)",
		kind = "attack",
		direction = "up",
		description = "A simple vertical slash, from down to up.",
	},
	{
		id = "downSlash",
		assetId = "rbxassetid://138466525319549",
		animationId = "downSlash",
		name = "Slash (Down)",
		kind = "attack",
		direction = "down",
		description = "A simple vertical slash, from up to down.",
	},
	{
		id = "upRightSlash",
		assetId = "rbxassetid://102923500654052",
		name = "Slash (Up Right)",
		kind = "attack",
		direction = "upRight",
		description = "A simple diagonal slash, from down left to up right.",
	},
	{
		id = "upLeftSlash",
		assetId = "rbxassetid://111339536159860",
		name = "Slash (Up Left)",
		kind = "attack",
		direction = "upLeft",
		description = "A simple diagonal slash, from down right to up left.",
	},
	{
		id = "downLeftSlash",
		assetId = "rbxassetid://73617879790277",
		name = "Slash (Down Left)",
		kind = "attack",
		direction = "downLeft",
		description = "A simple diagonal slash, from up right to down left.",
	},
	{
		id = "downRightSlash",
		assetId = "rbxassetid://97107896466883",
		name = "Slash (Down Right)",
		kind = "attack",
		direction = "downRight",
		description = "A simple diagonal slash, from up left to down right.",
	},
	
	-- Tarnished
	{
		id = "tarnishedRight",
		assetId = "rbxassetid://87593220907984",
		animationId = "tarnishedRight",
		name = "Tarnished's Slash (Right)",
		kind = "attack",
		direction = "right",
		description = "A simple horizontal slash, from left to right.",
	},
	{
		id = "tarnishedLeft",
		assetId = "rbxassetid://95127690189373",
		animationId = "tarnishedLeft",
		name = "Tarnished's Slash (Left)",
		kind = "attack",
		direction = "left",
		description = "A simple horizontal slash, from right to left.",
	},
	{
		id = "tarnishedUp",
		assetId = "rbxassetid://100591332217715",
		animationId = "tarnishedUp",
		name = "Tarnished's Slash (Up)",
		kind = "attack",
		direction = "up",
		description = "A simple vertical slash, from down to up.",
	},
	{
		id = "tarnishedDown",
		assetId = "rbxassetid://138466525319549",
		animationId = "tarnishedDown",
		name = "Tarnished's Slash (Down)",
		kind = "attack",
		direction = "down",
		description = "A simple vertical slash, from up to down.",
	},
}